import { describe, expect, it } from 'vitest';
import { GeneratedQuestionEntity } from '@/server/infrastructure/database';
import { groupIntoModules, UNCATEGORIZED_MODULE_NAME } from './group-into-modules';

function makeQuestion(id: string, sourceSection: string | null): GeneratedQuestionEntity {
  const q = new GeneratedQuestionEntity();
  q.id = id;
  q.processingSessionId = 'session-1';
  q.subjectId = null;
  q.questionText = `question ${id}`;
  q.optionsJson = { A: 'a', B: 'b' };
  q.correctAnswer = 'A';
  q.explanation = null;
  q.questionType = 'multiple_choice';
  q.bloomsLevel = null;
  q.sourcePageRange = '1';
  q.sourceSection = sourceSection;
  q.answerSource = null;
  q.confidenceScore = 0.9;
  q.generationMethod = 'exam_extraction_with_key';
  q.isAutoGenerated = true;
  q.isHumanEdited = false;
  q.isReviewFlagged = false;
  q.notes = null;
  q.linkedExamTypeId = null;
  q.batchIndex = null;
  return q;
}

describe('groupIntoModules (FR-PDF-9/FR-PDF-10)', () => {
  it('groups by raw source_section when no declared modules are supplied', () => {
    const eligible = [makeQuestion('1', 'Chapter 1'), makeQuestion('2', 'Chapter 1'), makeQuestion('3', 'Chapter 2')];
    const { modules, questions } = groupIntoModules('exam-1', eligible, undefined);

    expect(modules).toHaveLength(2);
    const chapter1 = modules.find((m) => m.moduleName === 'Chapter 1')!;
    const chapter2 = modules.find((m) => m.moduleName === 'Chapter 2')!;
    expect(chapter1.questionCount).toBe(2);
    expect(chapter2.questionCount).toBe(1);
    expect(questions).toHaveLength(3);
    expect(questions.every((q) => q.examTypeId === 'exam-1')).toBe(true);
    expect(questions.every((q) => q.questionKey.startsWith('gq_'))).toBe(true);
  });

  it('falls back to the UNCATEGORIZED_MODULE_NAME for a null source_section', () => {
    const { modules } = groupIntoModules('exam-1', [makeQuestion('1', null)], undefined);
    expect(modules).toHaveLength(1);
    expect(modules[0].moduleName).toBe(UNCATEGORIZED_MODULE_NAME);
  });

  it('rolls up raw sections into a declared module name', () => {
    const eligible = [makeQuestion('1', 'Ch1'), makeQuestion('2', 'Ch2'), makeQuestion('3', 'Ch3')];
    const { modules } = groupIntoModules('exam-1', eligible, [{ name: 'Unit 1', sourceSections: ['Ch1', 'Ch2'] }]);

    const unit1 = modules.find((m) => m.moduleName === 'Unit 1')!;
    const ch3 = modules.find((m) => m.moduleName === 'Ch3')!;
    expect(unit1.questionCount).toBe(2);
    expect(ch3.questionCount).toBe(1);
    expect(modules).toHaveLength(2);
  });

  it('derives question_key deterministically from the source generated_question id', () => {
    const { questions } = groupIntoModules('exam-1', [makeQuestion('abc-123', 'S')], undefined);
    expect(questions[0].questionKey).toBe('gq_abc-123');
    expect(questions[0].sourceGeneratedQuestionId).toBe('abc-123');
  });

  it('returns empty modules/questions for an empty eligible list', () => {
    const { modules, questions } = groupIntoModules('exam-1', [], undefined);
    expect(modules).toEqual([]);
    expect(questions).toEqual([]);
  });
});
