import { NextResponse, type NextRequest } from 'next/server';
import { requireTenantId, withTenantContext } from '@/server/context';
import { requireTenantUser } from '@/server/auth';
import { requirePermission } from '@/server/rbac';
import { requireFeatureLimit } from '@/server/platform/usage';
import { getFinalizeExamService } from '@/server/pdf-processing';
import type { FinalizeExamInput, FinalizeExamModuleInput } from '@/server/pdf-processing';
import { parseJsonBody, requireInt, requireString, optionalString, optionalBoolean } from '@/server/common/http/validate';
import { requireStringIdArray } from '@/server/common/http/id-array';
import { ValidationFailedError } from '@/server/common/errors/domain-error';

/** `POST /api/pdf-processing/sessions/:id/finalize` — tenant-realm, requires `exams.finalize`
 * (FR-PDF-9, LLD §7.3/§8.5, migration plan Phase 6, sub-slice "6c"). `201` (a new Exam Type was
 * genuinely created), matching legacy's `HttpStatus.CREATED`.
 *
 * **`exams.create` feature-usage limit** (FR-PKG-5): checked/incremented via `requireFeatureLimit`
 * immediately after the permission check — matches legacy's `@RequiresFeature('exams.create')` guard
 * order on `PdfProcessingController.finalizeSession` (finalize creates a new Exam Type exactly like the
 * ZIP-import path does, so it shares that same feature/quota, not a separate one). Closes the gap this
 * route's own doc comment previously flagged (no `FeatureLimitGuard`-equivalent existed) and Phase 10's
 * own e2e validation pass re-confirmed still open (see `docs/plans/nextjs-rewrite-phase10-plan.md`'s
 * "Post-e2e closure" section).
 *
 * **Rate limiting**: this app has no rate-limiting middleware anywhere yet (a pre-existing,
 * migration-plan-wide gap) — flagged explicitly here since finalize triggers a real (if best-effort)
 * embeddings call via `QuestionBankIndexingService`. The practical bound today is the
 * `exams.finalize` permission gate plus the tenant's own `exams.create` feature-limit quota above.
 */
export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }): Promise<Response> {
  return withTenantContext(request, async () => {
    const principal = await requireTenantUser(request);
    await requirePermission(principal.userId, 'exams.finalize');
    await requireFeatureLimit(requireTenantId(), 'exams.create');
    const { id } = await params;
    const body = await parseJsonBody(request);

    const input: FinalizeExamInput = {
      examName: requireString(body.examName, 'examName', { min: 1, max: 200 }),
      description: optionalString(body.description, 'description', { max: 1000 }),
      totalMinutes: requireInt(body.totalMinutes, 'totalMinutes', { min: 1, max: 1000 }),
      totalQuestions: requireInt(body.totalQuestions, 'totalQuestions', { min: 1, max: 10_000 }),
      minConfidence: requireMinConfidence(body.minConfidence),
      autoGeneratedOnly: optionalBoolean(body.autoGeneratedOnly, 'autoGeneratedOnly'),
      modules: validateModules(body.modules),
      curriculumLinks: validateCurriculumLinks(body.curriculumLinks),
    };

    const result = await getFinalizeExamService().finalize(id, input);
    return NextResponse.json(result, { status: 201 });
  });
}

function requireMinConfidence(value: unknown): number {
  if (typeof value !== 'number' || Number.isNaN(value) || value < 0 || value > 1) {
    throw new ValidationFailedError([{ field: 'minConfidence', constraint: 'minConfidence must be a number between 0 and 1.' }]);
  }
  return value;
}

function validateModules(value: unknown): FinalizeExamModuleInput[] | undefined {
  if (value === undefined) return undefined;
  if (!Array.isArray(value)) {
    throw new ValidationFailedError([{ field: 'modules', constraint: 'modules must be an array.' }]);
  }
  return value.map((raw, index) => {
    if (typeof raw !== 'object' || raw === null) {
      throw new ValidationFailedError([{ field: `modules[${index}]`, constraint: 'each module must be an object.' }]);
    }
    const record = raw as Record<string, unknown>;
    return {
      name: requireString(record.name, `modules[${index}].name`, { min: 1, max: 200 }),
      sourceSections: requireStringIdArray(record.sourceSections, `modules[${index}].sourceSections`),
    };
  });
}

function validateCurriculumLinks(value: unknown): FinalizeExamInput['curriculumLinks'] {
  if (value === undefined) return undefined;
  if (!Array.isArray(value)) {
    throw new ValidationFailedError([{ field: 'curriculumLinks', constraint: 'curriculumLinks must be an array.' }]);
  }
  return value.map((raw, index) => {
    if (typeof raw !== 'object' || raw === null) {
      throw new ValidationFailedError([{ field: `curriculumLinks[${index}]`, constraint: 'each link must be an object.' }]);
    }
    const record = raw as Record<string, unknown>;
    return {
      curriculumId: requireString(record.curriculumId, `curriculumLinks[${index}].curriculumId`, { min: 1, max: 36 }),
      // Deliberately NOT bounds-checked to [1,10] here (only type-checked as an integer) — FR-AUTH-4's
      // 1-10 range is `FinalizeExamService.validateCurriculumLinks`'s own domain rule, surfaced as the
      // specific `INVALID_CONTEXT_WEIGHT` error naming the offending value. Enforcing the same bound at
      // this HTTP boundary too would shadow that domain error with a generic `VALIDATION_FAILED` before
      // the service ever runs, which this dispatch's own integration test caught.
      contextWeight: requireInt(record.contextWeight, `curriculumLinks[${index}].contextWeight`, { min: Number.MIN_SAFE_INTEGER, max: Number.MAX_SAFE_INTEGER }),
      applicableModules: record.applicableModules === undefined ? undefined : requireStringIdArray(record.applicableModules, `curriculumLinks[${index}].applicableModules`),
    };
  });
}
