import * as client from "openid-client";
import { SsoAuthenticationFailedError, SsoNotConfiguredError } from "@nextbot/contracts";
import type { TenantContext } from "@nextbot/db";
import { getSsoConnection, type SsoConnectionRow } from "../infrastructure/sso-connection-repository.js";
import { decryptOidcClientSecret } from "./sso-connection.js";

/**
 * OIDC SSO (FR-SEC-10) via `openid-client` (panva, MIT, actively maintained —
 * cleared against the ADR's dependency maturity bar; not named in the LLD's
 * library table because SSO/SCIM's concrete protocol library wasn't decided at
 * LLD time, see this module's README entry).
 *
 * `openid-client` v6's functional API (`discovery()`/`buildAuthorizationUrl()`/
 * `authorizationCodeGrant()`) is re-derived per call rather than cached across
 * requests — an admin can change the connection's issuer/client at any time, and
 * a cached `Configuration` pointed at a now-stale issuer would silently keep
 * accepting tokens from the old IdP, which is exactly the "misconfigured IdP
 * still lets someone in" failure mode FR-SEC-10 requires failing closed against.
 */

async function loadConfiguration(ctx: TenantContext) {
  const connection = await getSsoConnection(ctx);
  if (!connection || connection.protocol !== "Oidc" || connection.status !== "Active") {
    throw new SsoNotConfiguredError();
  }
  if (!connection.oidcIssuerUrl || !connection.oidcClientId) throw new SsoNotConfiguredError();
  const clientSecret = await decryptOidcClientSecret(ctx, connection);
  const config = await client.discovery(new URL(connection.oidcIssuerUrl), connection.oidcClientId, undefined, client.ClientSecretPost(clientSecret));
  return { config, connection };
}

/** Builds the redirect URL that starts the OIDC authorization-code flow.
 * `state`/`nonce` are generated by the caller (the login route) and persisted in
 * a short-lived cookie so the callback step can validate them against replay/CSRF
 * — never trusted from the query string alone. */
export async function buildOidcAuthorizationUrl(
  ctx: TenantContext,
  input: { redirectUri: string; state: string; nonce: string },
): Promise<string> {
  const { config } = await loadConfiguration(ctx);
  const url = client.buildAuthorizationUrl(config, {
    redirect_uri: input.redirectUri,
    scope: "openid email profile",
    state: input.state,
    nonce: input.nonce,
  });
  return url.href;
}

export interface OidcCallbackResult {
  subject: string;
  email: string | null;
  groups: string[];
  connection: SsoConnectionRow;
}

/**
 * Completes the OIDC callback: exchanges the authorization code, validates the
 * ID token (issuer/audience/signature/nonce — all enforced internally by
 * `authorizationCodeGrant`'s `checks`), and extracts the claims this module's
 * login-resolution step needs. ANY failure here (bad code, signature mismatch,
 * expired/replayed nonce, network failure reaching the IdP) is deliberately
 * collapsed to the single generic `SsoAuthenticationFailedError` — fail closed,
 * never a partial/best-effort login.
 *
 * @throws {SsoAuthenticationFailedError} on any validation failure.
 */
export async function completeOidcCallback(
  ctx: TenantContext,
  input: { currentUrl: URL; expectedState: string; expectedNonce: string },
): Promise<OidcCallbackResult> {
  try {
    const { config, connection } = await loadConfiguration(ctx);
    const tokens = await client.authorizationCodeGrant(config, input.currentUrl, {
      expectedState: input.expectedState,
      expectedNonce: input.expectedNonce,
    });
    const claims = tokens.claims();
    if (!claims?.sub) throw new Error("ID token missing sub claim");

    const groupClaim = connection.groupClaimName ? (claims as Record<string, unknown>)[connection.groupClaimName] : undefined;
    const groups = Array.isArray(groupClaim) ? groupClaim.filter((g): g is string => typeof g === "string") : [];

    return {
      subject: claims.sub,
      email: typeof claims.email === "string" ? claims.email : null,
      groups,
      connection,
    };
  } catch (err) {
    if (err instanceof SsoNotConfiguredError) throw err;
    throw new SsoAuthenticationFailedError();
  }
}
