import { Column, CreateDateColumn, Entity, PrimaryColumn, UpdateDateColumn } from 'typeorm';

/**
 * TypeORM mapping for the tenant-schema `generated_question` table (migration plan Phase 6, sub-slice
 * "6a", migration `20260815000007-create-pdf-processing-tables.ts`) — ported from
 * `legacy/api/src/modules/pdf-processing/infrastructure/entities/generated-question.entity.ts`.
 * `answerSource`/`confidenceScore`/`generationMethod` are populated exclusively by
 * `ExamExtractionService` this sub-slice (`'provided'`/`'inferred'`, `'exam_extraction_with_key'`/
 * `'exam_extraction_inferred'`) — `subjectId` is always `null` from this writer (FR-PDF-7 subject-
 * mapping only applies to the `Lesson` branch, sub-slice 6b's own scope). `generationMethod` is a plain
 * `varchar`, not an enum, matching legacy's own "a future generation method never requires a migration"
 * rationale.
 *
 * Plain FK-shaped columns (`subjectId`/`linkedExamTypeId`), never a hydrated relation object, matching
 * `ExamTypeEntity`'s established "plain FK column, no domain-module import from an entity file"
 * convention.
 */
@Entity({ name: 'generated_question' })
export class GeneratedQuestionEntity {
  @PrimaryColumn({ type: 'char', length: 36 })
  id!: string;

  @Column({ name: 'processing_session_id', type: 'char', length: 36 })
  processingSessionId!: string;

  @Column({ name: 'subject_id', type: 'int', nullable: true })
  subjectId!: number | null;

  @Column({ name: 'question_text', type: 'text' })
  questionText!: string;

  /** `{"A":"...","B":"...",...}` — stored keyed-by-option-letter, matching
   * `ExamTypeQuestionEntity.optionsJson`'s identical shape, so both tables can feed the same downstream
   * question-rendering code once a later sub-slice finalizes a Generated Question into one. */
  @Column({ name: 'options_json', type: 'json' })
  optionsJson!: Record<string, string>;

  @Column({ name: 'correct_answer', type: 'varchar', length: 10 })
  correctAnswer!: string;

  @Column({ type: 'text', nullable: true })
  explanation!: string | null;

  @Column({ name: 'question_type', type: 'varchar', length: 50, default: 'multiple_choice' })
  questionType!: string;

  @Column({ name: 'blooms_level', type: 'tinyint', nullable: true })
  bloomsLevel!: number | null;

  @Column({ name: 'source_page_range', type: 'varchar', length: 50, nullable: true })
  sourcePageRange!: string | null;

  @Column({ name: 'source_section', type: 'varchar', length: 200, nullable: true })
  sourceSection!: string | null;

  @Column({ name: 'answer_source', type: 'enum', enum: ['provided', 'inferred'], nullable: true })
  answerSource!: 'provided' | 'inferred' | null;

  @Column({ name: 'confidence_score', type: 'decimal', precision: 4, scale: 3, default: 0.8 })
  confidenceScore!: number;

  @Column({ name: 'generation_method', type: 'varchar', length: 50 })
  generationMethod!: string;

  @Column({ name: 'is_auto_generated', type: 'tinyint', width: 1, default: 1 })
  isAutoGenerated!: boolean;

  @Column({ name: 'is_human_edited', type: 'tinyint', width: 1, default: 0 })
  isHumanEdited!: boolean;

  @Column({ name: 'is_review_flagged', type: 'tinyint', width: 1, default: 0 })
  isReviewFlagged!: boolean;

  @Column({ type: 'varchar', length: 1000, nullable: true })
  notes!: string | null;

  /** No declared FK, matching legacy's identical LLD DDL choice — `exam_type` linkage happens once a
   * later sub-slice's finalize/append flow writes this column; nothing in this sub-slice ever sets it. */
  @Column({ name: 'linked_exam_type_id', type: 'char', length: 36, nullable: true })
  linkedExamTypeId!: string | null;

  /** Always `null` from `ExamExtractionService` (per-page, not batched); populated only by a batched
   * generation branch (lesson-generation, sub-slice 6b). */
  @Column({ name: 'batch_index', type: 'int', nullable: true })
  batchIndex!: number | null;

  @CreateDateColumn({ name: 'created_at', type: 'datetime', precision: 3 })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'datetime', precision: 3 })
  updatedAt!: Date;
}
