import { tenantFetch } from './http-client';

/** Local mirror of `PdfProcessingSessionSummary` (server: `@/server/pdf-processing`'s
 * `domain/pdf-processing.types.ts`). */
export interface PdfProcessingSessionSummary {
  id: string;
  sourceFileName: string;
  status: 'Pending' | 'Extracting' | 'Classifying' | 'Processing' | 'Completed' | 'Failed';
  contentTypeHint: 'Lesson' | 'Exam' | 'Reference' | null;
  contentType: 'Lesson' | 'Exam' | 'Reference' | null;
  errorCode: string | null;
  errorMessage: string | null;
  detectedTopics: string[] | null;
  estimatedQuestionsPerPage: number | null;
  pageCount: number | null;
  tokensUsed: number;
  totalCost: number;
  fileHash: string;
  reusedFromSessionId: string | null;
  initiatedByUserId: string | null;
  totalQuestions: number;
  successfulQuestions: number;
  createdAt: string;
  completedAt: string | null;
}

export interface UploadPdfResult {
  sessionId: string;
  status: PdfProcessingSessionSummary['status'];
}

export interface UploadPdfOptions {
  contentTypeHint?: 'Lesson' | 'Exam' | 'Reference';
  subjectId?: number;
  curriculumId?: string;
  forceReprocess?: boolean;
}

/** `GET /api/pdf-processing/sessions`. */
export function listSessions(): Promise<PdfProcessingSessionSummary[]> {
  return tenantFetch<PdfProcessingSessionSummary[]>('/api/pdf-processing/sessions', { method: 'GET' });
}

/** `GET /api/pdf-processing/sessions/:id`. */
export function getSession(id: string): Promise<PdfProcessingSessionSummary> {
  return tenantFetch<PdfProcessingSessionSummary>(`/api/pdf-processing/sessions/${encodeURIComponent(id)}`, { method: 'GET' });
}

/**
 * `POST /api/pdf-processing/upload` — multipart PDF upload. Same Fetch `FormData` client-side pattern
 * as `createExamTypeFromZip`; same documented "no first-class upload-progress event for a `FormData`
 * body" UX deviation from legacy's Angular `HttpClient.reportProgress` — a single indeterminate
 * "Uploading…" state for the whole request duration.
 */
export function uploadPdf(file: File, options: UploadPdfOptions = {}): Promise<UploadPdfResult> {
  const formData = new FormData();
  formData.append('file', file);
  if (options.contentTypeHint) formData.append('contentTypeHint', options.contentTypeHint);
  if (options.subjectId !== undefined) formData.append('subjectId', String(options.subjectId));
  if (options.curriculumId) formData.append('curriculumId', options.curriculumId);
  if (options.forceReprocess !== undefined) formData.append('forceReprocess', String(options.forceReprocess));

  return tenantFetch<UploadPdfResult>('/api/pdf-processing/upload', { method: 'POST', body: formData });
}

/**
 * Sub-slice "6c" additions (FR-PDF-8/9/10) — question review/edit/bulk-actions,
 * finalize-into-Exam-Type, append-to-an-existing-Exam-Type. Local mirrors of `server/pdf-processing`'s
 * own wire types.
 */

export interface GeneratedQuestionImage {
  id: string;
  storageKey: string;
  altText: string;
  caption: string | null;
  position: 'question_text' | 'option' | 'explanation';
  optionKey: string | null;
  width: number | null;
  height: number | null;
}

export interface GeneratedQuestionSummary {
  id: string;
  processingSessionId: string;
  subjectId: number | null;
  questionText: string;
  options: Record<string, string>;
  correctAnswer: string;
  explanation: string | null;
  questionType: string;
  bloomsLevel: number | null;
  sourcePageRange: string | null;
  sourceSection: string | null;
  answerSource: 'provided' | 'inferred' | null;
  confidenceScore: number;
  generationMethod: string;
  isAutoGenerated: boolean;
  isHumanEdited: boolean;
  isReviewFlagged: boolean;
  notes: string | null;
  linkedExamTypeId: string | null;
  createdAt: string;
  updatedAt: string;
  images: GeneratedQuestionImage[];
}

export interface PaginatedGeneratedQuestions {
  items: GeneratedQuestionSummary[];
  total: number;
  page: number;
  pageSize: number;
}

/** `GET /api/pdf-processing/sessions/:id/questions?page=&pageSize=`. */
export function listQuestions(sessionId: string, page = 1, pageSize = 20): Promise<PaginatedGeneratedQuestions> {
  return tenantFetch<PaginatedGeneratedQuestions>(
    `/api/pdf-processing/sessions/${encodeURIComponent(sessionId)}/questions?page=${page}&pageSize=${pageSize}`,
    { method: 'GET' },
  );
}

export interface EditGeneratedQuestionInput {
  questionText?: string;
  options?: Record<string, string>;
  correctAnswer?: string;
  explanation?: string | null;
  bloomsLevel?: number | null;
  notes?: string | null;
}

/** `PATCH /api/pdf-processing/questions/:id`. */
export function editQuestion(id: string, patch: EditGeneratedQuestionInput): Promise<GeneratedQuestionSummary> {
  return tenantFetch<GeneratedQuestionSummary>(`/api/pdf-processing/questions/${encodeURIComponent(id)}`, {
    method: 'PATCH',
    body: JSON.stringify(patch),
  });
}

/** `POST /api/pdf-processing/questions/:id/flag` / `.../unflag`. */
export function setQuestionFlag(id: string, flagged: boolean): Promise<void> {
  return tenantFetch<void>(`/api/pdf-processing/questions/${encodeURIComponent(id)}/${flagged ? 'flag' : 'unflag'}`, { method: 'POST' });
}

/** `POST /api/pdf-processing/sessions/:id/questions/bulk-delete`. */
export function bulkDeleteQuestions(sessionId: string, ids: string[]): Promise<{ deletedCount: number }> {
  return tenantFetch<{ deletedCount: number }>(`/api/pdf-processing/sessions/${encodeURIComponent(sessionId)}/questions/bulk-delete`, {
    method: 'POST',
    body: JSON.stringify({ ids }),
  });
}

/** `POST /api/pdf-processing/sessions/:id/questions/regenerate`. */
export function bulkRegenerateQuestions(sessionId: string, ids: string[]): Promise<{ regeneratedCount: number; requestedCount: number }> {
  return tenantFetch<{ regeneratedCount: number; requestedCount: number }>(
    `/api/pdf-processing/sessions/${encodeURIComponent(sessionId)}/questions/regenerate`,
    { method: 'POST', body: JSON.stringify({ ids }) },
  );
}

export interface FinalizeExamModuleInput {
  name: string;
  sourceSections: string[];
}

export interface FinalizeCurriculumLinkInput {
  curriculumId: string;
  contextWeight: number;
  applicableModules?: string[];
}

export interface FinalizeExamInput {
  examName: string;
  description?: string;
  totalMinutes: number;
  totalQuestions: number;
  minConfidence: number;
  autoGeneratedOnly?: boolean;
  modules?: FinalizeExamModuleInput[];
  curriculumLinks?: FinalizeCurriculumLinkInput[];
}

export interface ExamModuleSummary {
  id: string;
  moduleName: string;
  questionCount: number;
}

export interface ExamTypeCurriculumLinkSummary {
  curriculumId: string;
  curriculumName: string;
  contextWeight: number;
  applicableModules: string[] | null;
}

export interface ExamTypeSummary {
  id: string;
  name: string;
  description: string | null;
  totalQuestions: number;
  totalMinutes: number;
  stageId: number | null;
  kind: string;
  origin: 'ZipImport' | 'AiPipeline';
  storagePath: string | null;
  pendingDeleteAt: string | null;
  createdAt: string;
  updatedAt: string;
  modules: ExamModuleSummary[];
  curriculumLinks: ExamTypeCurriculumLinkSummary[];
}

/** `POST /api/pdf-processing/sessions/:id/finalize`. */
export function finalizeSession(sessionId: string, input: FinalizeExamInput): Promise<ExamTypeSummary> {
  return tenantFetch<ExamTypeSummary>(`/api/pdf-processing/sessions/${encodeURIComponent(sessionId)}/finalize`, {
    method: 'POST',
    body: JSON.stringify(input),
  });
}

/**
 * Sub-slice "6d" addition — the reviewer "Find similar questions" tool. Local mirror of
 * `SimilarQuestionMatch` (server: `@/server/pdf-processing`'s `similar-questions.service.ts`).
 */
export interface SimilarQuestionMatch {
  score: number;
  examTypeName: string;
  moduleName: string;
  questionText: string;
}

/** `GET /api/pdf-processing/questions/:id/similar`. */
export function findSimilarQuestions(generatedQuestionId: string): Promise<SimilarQuestionMatch[]> {
  return tenantFetch<SimilarQuestionMatch[]>(`/api/pdf-processing/questions/${encodeURIComponent(generatedQuestionId)}/similar`, { method: 'GET' });
}

/** `POST /api/pdf-processing/sessions/:id/append`. `idempotencyKey`, if supplied, is sent as the
 * `Idempotency-Key` header (LLD §7.6) — safe to retry the identical call with the same key. */
export function appendToExamType(
  sessionId: string,
  input: { examTypeId: string; ids: string[] },
  idempotencyKey?: string,
): Promise<ExamTypeSummary> {
  const headers: Record<string, string> = {};
  if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;
  return tenantFetch<ExamTypeSummary>(`/api/pdf-processing/sessions/${encodeURIComponent(sessionId)}/append`, {
    method: 'POST',
    headers,
    body: JSON.stringify(input),
  });
}
