/**
 * `POST /api/public/v1/conversations/{id}/turns` (api.md §4.3) — everything
 * short of actually calling `shj3-ai` and streaming its response, which is
 * the route handler's job (piping a `ReadableStream` and filtering frames is
 * an I/O/framework concern, not business logic — see that route's own doc
 * comment). This use case owns every decision that can be made *before* the
 * upstream call: validation, handover-active/rate-limit/lock/dedupe.
 */

import { requireOwnConversation, ConversationNotFoundError } from "./conversation-not-found.js";
import type { PublicChannelKind } from "../domain/channel-key.js";
import { validatePostTurnInput, type TurnFieldError } from "../domain/turn-input.js";
import type { ConversationRepository } from "../ports/conversation-repository.js";
import type { EscalationRepository } from "../ports/escalation-repository.js";
import type { WidgetChannelRepository } from "../ports/widget-channel-repository.js";
import type { TurnCoordination } from "../ports/turn-coordination.js";

/** A live channel with no bound agent violates `CK_Channels_liveNeedsAgent` and should be unreachable in practice — surfaced as a clear, distinct error rather than a null-pointer if it ever is. */
export class ChannelNotConfiguredError extends Error {
  readonly code = "conversation.channel_not_configured";
  readonly status = 503;
  constructor() {
    super("This channel has no agent bound and cannot process turns.");
    this.name = "ChannelNotConfiguredError";
  }
}
export class HandoverActiveError extends Error {
  readonly code = "conversation.handover_active";
  readonly status = 409;
  constructor() {
    super("A human agent is holding this conversation; the composer is paused.");
    this.name = "HandoverActiveError";
  }
}
export class TurnInProgressError extends Error {
  readonly code = "conversation.turn_in_progress";
  readonly status = 409;
  constructor() {
    super("A turn is already in flight on this conversation.");
    this.name = "TurnInProgressError";
  }
}
export class ValidationFailedError extends Error {
  readonly code = "validation.failed";
  readonly status = 422;
  constructor(readonly errors: readonly TurnFieldError[]) {
    super(`${errors.length} field(s) failed validation.`);
    this.name = "ValidationFailedError";
  }
}
/** A real, if simple, per-conversation window (`ports/turn-coordination.ts`'s own doc comment on scope). */
export class RateLimitedError extends Error {
  readonly code = "rate_limit.exceeded";
  readonly status = 429;
  constructor() {
    super("Too many turns posted on this conversation in a short window.");
    this.name = "RateLimitedError";
  }
}

const TURN_RATE_WINDOW_SECONDS = 60;
const TURN_RATE_MAX_PER_WINDOW = 20;

export type PreparedTurn =
  | { readonly kind: "reattach"; readonly turnId: string }
  | {
      readonly kind: "proceed";
      readonly turnId: string;
      readonly agentId: string;
      readonly channel: "web" | "whatsapp";
    };

export class PostTurn {
  constructor(
    private readonly deps: {
      readonly conversations: ConversationRepository;
      readonly escalations: EscalationRepository;
      readonly widgetChannels: WidgetChannelRepository;
      readonly coordination: TurnCoordination;
    },
  ) {}

  /**
   * Throws one of the errors above, or returns a `PreparedTurn` describing
   * what the caller should do next. Always releases nothing itself — a
   * `"proceed"` result's lock must be released by the caller once the
   * upstream call finishes (`finally`), since only the caller knows when
   * that is.
   *
   * `newTurnId` is generated by the caller (the route handler, `app`-layer
   * code that may freely import the `ulid.js` adapter) and only *used* here
   * when this call actually proceeds to a new turn — never when it resolves
   * to a dedupe reattach. `application/` may not import an adapter directly
   * (architecture.md §4's swap test), so the id is threaded in rather than
   * minted inline, the same inversion `OpenConversation`/`RequestHandover`
   * apply via their own repositories' id-minting.
   */
  async prepare(input: {
    readonly conversationId: string;
    readonly sessionSubjectId: string;
    readonly channelKind: PublicChannelKind;
    readonly content: unknown;
    readonly inputMode: unknown;
    readonly chipId?: unknown;
    readonly clientTurnId: unknown;
    readonly newTurnId: string;
    readonly now: Date;
  }): Promise<PreparedTurn> {
    requireOwnConversation(input.sessionSubjectId, input.conversationId);

    const errors = validatePostTurnInput(input);
    if (errors.length > 0) throw new ValidationFailedError(errors);
    const clientTurnId = input.clientTurnId as string;

    const conversation = await this.deps.conversations.findById(input.conversationId);
    if (!conversation) throw new ConversationNotFoundError();

    const openTicket = await this.deps.escalations.findOpenForConversation(input.conversationId);
    if (openTicket?.status === "Active") throw new HandoverActiveError();

    const existingTurnId = await this.deps.coordination.findDedupedTurn(
      input.conversationId,
      clientTurnId,
    );
    if (existingTurnId) return { kind: "reattach", turnId: existingTurnId };

    const rateCount = await this.deps.coordination.incrementTurnRateCount(
      input.conversationId,
      TURN_RATE_WINDOW_SECONDS,
    );
    if (rateCount > TURN_RATE_MAX_PER_WINDOW) throw new RateLimitedError();

    const locked = await this.deps.coordination.acquireTurnLock(input.conversationId);
    if (!locked) throw new TurnInProgressError();

    const channel = await this.deps.widgetChannels.findChannelByKind(input.channelKind);
    if (!channel?.boundAgentId) {
      await this.deps.coordination.releaseTurnLock(input.conversationId);
      throw new ChannelNotConfiguredError();
    }

    await this.deps.coordination.rememberClientTurnId(
      input.conversationId,
      clientTurnId,
      input.newTurnId,
    );

    return {
      kind: "proceed",
      turnId: input.newTurnId,
      agentId: channel.boundAgentId,
      channel: input.channelKind === "WhatsApp" ? "whatsapp" : "web",
    };
  }

  async releaseLock(conversationId: string): Promise<void> {
    await this.deps.coordination.releaseTurnLock(conversationId);
  }
}
